name: tarific

services:
  mcp_chatbot_backend:
    container_name: mcp-chatbot
    build:
      context: ../MCP-client
      dockerfile: Dockerfile.dev
    expose:
      - "8001"
    env_file:
      - ../MCP-client/.env
    depends_on:
      mcp_server_backend:
        condition: service_healthy
    restart: on-failure
    networks:
      - tariff-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://mcp_chatbot_backend:8001/chat/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

  mcp_gateway_backend:
    container_name: mcp-gateway
    build:
      context: ../MCP-Gateway
      dockerfile: Dockerfile.dev
    expose:
      - "8090"
    env_file:
      - ../MCP-Gateway/.env
    environment:
      BASE_URL: "http://mcp_server_backend:8000"
    restart: on-failure
    networks:
      - tariff-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://mcp_gateway_backend:8090/mcp/api/v1/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

  mcp_server_backend:
    container_name: mcp-server
    build:
      context: ../MCP-Server
      dockerfile: Dockerfile.dev
    expose:
      - "8000"
    env_file:
      - ../MCP-Server/.env
    restart: on-failure
    networks:
      - tariff-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://mcp_server_backend:8000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

  spring_boot_backend:
    container_name: tariff-backend
    build:
      context: ../tariff-backend
      dockerfile: Dockerfile.dev
    expose:
      - "8080"
    env_file:
      - ../tariff-backend/.env
    restart: on-failure
    networks:
      - tariff-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://spring_boot_backend:8080/api/v1/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
   
  nginx-frontend:
    container_name: tariff-frontend
    build:
      context: ../tariff-frontend
      dockerfile: Dockerfile.dev
    ports:
      - "80:80"
      # - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      spring_boot_backend:
        condition: service_healthy
    networks:
      - tariff-network

networks:
  tariff-network:
    driver: bridge
