# --- Stage 1: Builder ---
FROM ghcr.io/astral-sh/uv:python3.12-bookworm AS builder

WORKDIR /app
COPY . .

# Create virtual environment and sync dependencies
RUN uv sync --frozen

# --- Stage 2: Runtime ---
FROM ghcr.io/astral-sh/uv:python3.12-bookworm AS runtime

ARG BASE_URL
ENV BASE_URL=${BASE_URL}

WORKDIR /app
COPY --from=builder /app /app
COPY --from=builder /usr/local/bin/uv /usr/local/bin/uv

EXPOSE 8090
ENTRYPOINT ["uv", "run", "main.py"]
