import os
import os.path
import json
import base64
import asyncio  # <-- Required for async operation
from email.mime.text import MIMEText

# --- NEW: Imports for Desktop App / token.json flow ---
from google.oauth2.credentials import Credentials
from google.auth.transport.requests import Request
# --- REMOVED: service_account import ---
from googleapiclient.discovery import build
from googleapiclient.errors import HttpError

# This is the only scope we need for this tool
SCOPES = ['https://www.googleapis.com/auth/gmail.send']
# This is the token file generated by your original send_email.py
TOKEN_PATH = 'token.json'

# --- Synchronous Helper Functions ---

def _get_gmail_service_sync():
    """
    (Sync) Authenticates using the "Desktop App" flow
    with an *existing* token.json.
    Returns (service, error_message)
    """
    creds = None
    
    # 1. Check if token.json exists
    if not os.path.exists(TOKEN_PATH):
        msg = (f"Error: {TOKEN_PATH} not found in server root. "
               f"This tool requires an existing {TOKEN_PATH}. "
               "Please run your original send_email.py script (locally, not the server) one time to create it.")
        print(msg)
        return None, msg

    # 2. Load credentials from token.json
    try:
        creds = Credentials.from_authorized_user_file(TOKEN_PATH, SCOPES)
    except Exception as e:
        msg = (f"Error reading {TOKEN_PATH}. It might be corrupted. "
               f"Delete it and re-run the original send_email.py to re-create it. Error: {e}")
        print(msg)
        return None, msg

    # 3. Check if credentials are valid or need refresh
    try:
        if not creds.valid:
            if creds.expired and creds.refresh_token:
                print("Credentials expired. Refreshing token (this is non-interactive)...")
                # This is a non-browser, backend API call.
                creds.refresh(Request())
            else:
                msg = (f"Error: Credentials in {TOKEN_PATH} are not valid and have no refresh token. "
                       f"Please delete {TOKEN_PATH} and re-run the original send_email.py script to re-authenticate.")
                print(msg)
                return None, msg
    except Exception as e:
         msg = (f"Error refreshing token. Your permissions may have been revoked. "
                f"Delete {TOKEN_PATH} and re-run send_email.py. Error: {e}")
         print(msg)
         return None, msg

    # 4. Save the (potentially) refreshed credentials back to token.json
    try:
        with open(TOKEN_PATH, 'w') as token:
            token.write(creds.to_json())
        print("Token refreshed and saved.")
    except Exception as e:
        # Not a fatal error, we can proceed, but log it.
        print(f"Warning: Could not save refreshed token to {TOKEN_PATH}. Error: {e}")

    # 5. Build the service
    try:
        service = build('gmail', 'v1', credentials=creds)
        return service, None # Success
    except HttpError as error:
        msg = f'An error occurred building the Gmail service: {error}'
        print(msg)
        return None, msg


def _create_message_sync(sender, to, subject, message_text):
    """(Sync) Create a MIMEText object for sending an email."""
    message = MIMEText(message_text)
    message['to'] = to
    message['from'] = sender
    message['subject'] = subject
    
    raw_message = base64.urlsafe_b64encode(message.as_bytes()).decode()
    return {'raw': raw_message}

def _send_message_sync(service, user_id, message):
    """
    (Sync) Send an email message using the Gmail API.
    Returns (sent_message, error_message)
    """
    try:
        message = (service.users().messages().send(userId=user_id, body=message)
                   .execute())
        print(f'Message Id: {message["id"]}')
        return message, None  # Success
    except HttpError as error:
        msg = f'An error occurred sending the email: {error}'
        print(msg)
        return None, msg

# --- Main Asynchronous Tool Function ---

async def send_email_logic(to_email: str, subject: str, body: str) -> dict:
    """
    This is the main async function that will be imported by mcp_server.py.
    It runs all blocking I/O (auth and send) in separate threads.
    """
    print("Attempting to authenticate with Gmail (Desktop App / token.json flow)...")
    
    # Run the blocking auth function in a separate thread
    service, auth_error = await asyncio.to_thread(_get_gmail_service_sync)
    
    if auth_error:
        return {"status": "error", "detail": auth_error}
    
    print("Authentication successful.")
    
    # create_message is fast, no thread needed
    message_to_send = _create_message_sync(
        sender="me", 
        to=to_email, 
        subject=subject, 
        message_text=body
    )
    
    print(f"Sending message to: {to_email}...")
    
    # Run the blocking 'send' function in a separate thread
    sent_message, send_error = await asyncio.to_thread(
        _send_message_sync, service, "me", message_to_send
    )
    
    if send_error:
        return {"status": "error", "detail": send_error}
        
    msg_id = sent_message['id']
    print(f"Email sent successfully. Message ID: {msg_id}")
    return {
        "status": "success", 
        "message_id": msg_id,
        "to": to_email
    }
