from io import BytesIO
from reportlab.pdfgen import canvas
from reportlab.lib.utils import ImageReader
from reportlab.lib.pagesizes import A4
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Image, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_CENTER, TA_JUSTIFY, TA_LEFT
from reportlab.lib import colors
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.pdfbase import pdfmetrics
from fastapi import Response
import requests
import re
import html
import os
from bs4 import BeautifulSoup

# --- Font Registration ---
fonts_dir = os.path.join(os.path.dirname(__file__), '..', 'utils', 'fonts')

# Define font paths and register them
FONT_MAPPING = {
    'latin': 'NotoSans-Regular.ttf',
    'cjk': 'NotoSansSC-Regular.ttf',
    'tamil': 'NotoSansTamil-Regular.ttf'
}

# Register fonts if they exist
for name, filename in FONT_MAPPING.items():
    font_path = os.path.join(fonts_dir, filename)
    if os.path.exists(font_path):
        pdfmetrics.registerFont(TTFont(name, font_path))
        # Register font silently
        pass  # Font already registered above
    else:
        print(f"Font not found: {font_path}")

# --- Character Range Detection ---
def contains_cjk(text):
    """Check if text contains Chinese, Japanese, or Korean characters."""
    return any(0x4E00 <= ord(char) <= 0x9FFF for char in text)

def contains_tamil(text):
    """Check if text contains Tamil characters."""
    return any(0x0B80 <= ord(char) <= 0x0BFF for char in text)

def generate_scraped_content_pdf(html_content: str) -> Response:
    """
    Generate PDF from LLM-formatted scraped content.
    Specifically designed to handle content from the Jarvis formatting pipeline.
    
    Args:
        html_content: HTML content with article-content wrapper from LLM formatting
        
    Returns:
        FastAPI Response with PDF content
    """
    try:
        pdf_generator = ScrapedContentPDFGenerator(html_content)
        pdf_buffer = pdf_generator.generate_pdf()
        
        return Response(
            content=pdf_buffer.read(),
            media_type="application/pdf",
            headers={
                "Content-Disposition": "attachment; filename=scraped_content.pdf"
            }
        )
    except Exception as e:
        print(f"Error generating scraped content PDF: {e}")
        # Return error PDF with proper font support
        buffer = BytesIO()
        doc = SimpleDocTemplate(buffer, pagesize=A4)
        
        # Create temporary generator to access font-aware styling
        temp_generator = ScrapedContentPDFGenerator("")
        error_text = f"Error generating PDF: {str(e)}"
        error_style = temp_generator._get_style(error_text, 'ArticleBody')
        
        story = [Paragraph(error_text, error_style)]
        doc.build(story)
        buffer.seek(0)
        
        return Response(
            content=buffer.read(),
            media_type="application/pdf"
        )

class ScrapedContentPDFGenerator:
    """
    PDF generator specifically designed for scraped content from Jarvis formatting pipeline.
    Handles the complex HTML structure generated by the LLM content formatter.
    """
    
    def __init__(self, html_content: str):
        # Store full HTML content for source URL extraction
        self.full_html_content = html_content
        # Extract main content from LLM wrapper structure
        self.main_content = self._extract_article_content(html_content)
        self.pdf_buffer = BytesIO()
        self.doc = SimpleDocTemplate(self.pdf_buffer, pagesize=A4,
                                   rightMargin=72, leftMargin=72,
                                   topMargin=72, bottomMargin=72)
        self.styles = self._create_styles()
        self.story = []

    def _extract_article_content(self, html_content: str) -> str:
        """
        Extract the main article content from LLM wrapper structure.
        Looks for <div class="article-content"> wrapper.
        """
        # First try to extract from article-content wrapper
        match = re.search(r'<div class="article-content">(.*)</div>', html_content, re.DOTALL)
        if match:
            return match.group(1).strip()
        
        # Fallback: try content-container wrapper
        match = re.search(r'<div class="content-container">(.*)</div>', html_content, re.DOTALL)
        if match:
            return match.group(1).strip()
        
        # Final fallback: use entire content
        return html_content

    def _create_styles(self):
        """Create ReportLab styles for different content elements with multi-language font support."""
        styles = getSampleStyleSheet()
        
        # Create font-specific styles for different languages
        base_style_map = {
            'latin': 'latin',
            'cjk': 'cjk',
            'tamil': 'tamil'
        }
        
        for key, font_name in base_style_map.items():
            # Article headers with language-specific fonts
            styles.add(ParagraphStyle(
                name=f'ArticleH1-{key}',
                parent=styles['Heading1'],
                fontName=font_name,
                fontSize=18,
                leading=22,
                alignment=TA_CENTER,
                spaceAfter=16
            ))
            
            styles.add(ParagraphStyle(
                name=f'ArticleH2-{key}', 
                parent=styles['Heading2'],
                fontName=font_name,
                fontSize=16,
                leading=18,
                alignment=TA_CENTER,
                spaceAfter=12
            ))
            
            styles.add(ParagraphStyle(
                name=f'ArticleH3-{key}',
                parent=styles['Heading3'], 
                fontName=font_name,
                fontSize=14,
                leading=16,
                alignment=TA_CENTER,
                spaceAfter=10
            ))
            
            styles.add(ParagraphStyle(
                name=f'ArticleBody-{key}',
                parent=styles['Normal'],
                fontName=font_name,
                fontSize=11,
                leading=14,
                alignment=TA_LEFT,
                spaceAfter=8
            ))
            
            styles.add(ParagraphStyle(
                name=f'Blockquote-{key}',
                parent=styles['Normal'],
                fontName=font_name,
                fontSize=11,
                leading=14,
                alignment=TA_LEFT,
                leftIndent=20,
                rightIndent=20,
                spaceAfter=8
            ))
            
            styles.add(ParagraphStyle(
                name=f'SourceURL-{key}',
                parent=styles['Normal'],
                fontName=font_name,
                fontSize=10,
                leading=12,
                alignment=TA_CENTER,
                textColor='black'  # Changed to black for the base text
            ))
        
        return styles
    
    def _get_style(self, text, style_prefix='ArticleBody'):
        """
        Get the appropriate style based on text content to ensure proper font support.
        
        Args:
            text: Text content to analyze for character types
            style_prefix: Base style name (ArticleH1, ArticleH2, ArticleBody, etc.)
            
        Returns:
            ParagraphStyle: Style with appropriate font for the text content
        """
        if contains_cjk(text):
            return self.styles[f'{style_prefix}-cjk']
        if contains_tamil(text):
            return self.styles[f'{style_prefix}-tamil']
        return self.styles[f'{style_prefix}-latin']

    def generate_pdf(self) -> BytesIO:
        """Generate the PDF and return buffer."""
        self._process_content()
        self.doc.build(self.story)
        self.pdf_buffer.seek(0)
        return self.pdf_buffer

    def _process_content(self):
        """Process the HTML content and build the PDF story."""
        if not self.main_content:
            self.story.append(Paragraph("No content available", self._get_style("No content available")))
            return
        
        # Extract and add source URL at the top
        self._add_source_url()
        
        # Split content by img tags to handle images separately
        parts = re.split(r'(<img[^>]+>)', self.main_content)
        
        for part in parts:
            part = part.strip()
            if not part:
                continue
                
            if part.startswith('<img'):
                self._process_image(part)
            else:
                self._process_text_content(part)

    def _add_source_url(self):
        """Extract source URL from content and add it at the top of the PDF."""
        # Look for the source URL pattern in the FULL HTML content (not just article content)
        # Pattern matches: <div style="..."><strong>Source:</strong> <a href="..." target="_blank" style="...">...</a></div>
        source_match = re.search(r'<strong>Source:</strong>\s*<a href="([^"]+)"[^>]*target="_blank"[^>]*>([^<]+)</a>', self.full_html_content, re.IGNORECASE)
        
        if source_match:
            source_url = source_match.group(1)
            # Create properly formatted text: "Source:" in black, URL in blue with underline and proper anchor tags
            source_text = f'Source: <link href="{source_url}" color="blue"><u>{source_url}</u></link>'
            source_style = self._get_style(source_url, 'SourceURL')  # Use URL for font detection
            self.story.append(Paragraph(source_text, source_style))
            self.story.append(Spacer(1, 24))  # Add extra space after source

    def _process_image(self, img_tag: str):
        """Process image tags and add to PDF."""
        src_match = re.search(r'src="([^"]+)"', img_tag, re.IGNORECASE)
        if not src_match:
            return
            
        img_url = html.unescape(src_match.group(1))
        
        try:
            print(f"Processing image: {img_url}")
            response = requests.get(img_url, timeout=10)
            response.raise_for_status()
            
            image_file = BytesIO(response.content)
            img_reader = ImageReader(image_file)
            img_width, img_height = img_reader.getSize()
            image_file.seek(0)
            
            # Calculate sizing (max 450px width, 630px height)
            max_width = 450
            max_height = 630
            
            width_ratio = img_width / max_width if img_width > max_width else 1.0
            height_ratio = img_height / max_height if img_height > max_height else 1.0
            scaling_factor = max(width_ratio, height_ratio)
            
            new_width = img_width / scaling_factor
            new_height = img_height / scaling_factor
            
            img = Image(image_file, width=new_width, height=new_height)
            self.story.append(img)
            self.story.append(Spacer(1, 12))
            
        except Exception as e:
            print(f"Failed to process image {img_url}: {e}")
            error_text = f"[Failed to load image: {img_url}]"
            self.story.append(Paragraph(error_text, self._get_style(error_text)))
            self.story.append(Spacer(1, 12))

    def _process_text_content(self, content: str):
        """Process text content with various HTML elements."""
        if not content.strip():
            return
            
        # Normalize HTML tags for ReportLab compatibility
        content = self._normalize_html_tags(content)
        
        # Handle blockquotes separately for special styling
        blockquote_parts = re.split(r'<blockquote>(.*?)</blockquote>', content, flags=re.IGNORECASE | re.DOTALL)
        
        for i, part in enumerate(blockquote_parts):
            part = part.strip()
            if not part:
                continue
                
            is_blockquote = (i % 2 == 1)
            
            if is_blockquote:
                # Process blockquote content
                self._process_blockquote(part)
            else:
                # Process regular content by headers
                self._process_regular_content(part)

    def _process_blockquote(self, content: str):
        """Process blockquote content with special styling."""
        # Clean up the content
        content = self._clean_text_content(content)
        if content:
            self.story.append(Paragraph(f'<i>{content}</i>', self._get_style(content, 'Blockquote')))
            self.story.append(Spacer(1, 12))

    def _process_regular_content(self, content: str):
        """Process regular content, splitting by headers."""
        # Split by headers to handle them with proper styles
        header_parts = re.split(r'(<h[1-3]>.*?</h[1-3]>)', content, flags=re.IGNORECASE | re.DOTALL)
        
        for part in header_parts:
            part = part.strip()
            if not part:
                continue
                
            # Check if this is a header
            header_match = re.match(r'<h([1-3])>(.*?)</h\1>', part, flags=re.IGNORECASE | re.DOTALL)
            
            if header_match:
                level, text = header_match.groups()
                text = self._clean_text_content(text)
                style_name = f'ArticleH{level}'
                self.story.append(Paragraph(text, self._get_style(text, style_name)))
                self.story.append(Spacer(1, 8))
            else:
                # Regular content - process tables, lists, and paragraphs
                self._process_body_content(part)

    def _process_body_content(self, content: str):
        """Process body content including tables, lists, and paragraphs."""
        # Handle tables (convert to simple text representation)
        content = self._process_tables(content)
        
        # Handle lists (convert to simple text with bullets)
        content = self._process_lists(content)
        
        # Clean and add as paragraph
        content = self._clean_text_content(content)
        if content:
            self.story.append(Paragraph(content, self._get_style(content, 'ArticleBody')))
            self.story.append(Spacer(1, 8))

    def _process_tables(self, content: str) -> str:
        """Process HTML tables and replace with ReportLab Table objects."""
        soup = BeautifulSoup(content, 'html.parser')
        
        for table in soup.find_all('table'):
            # Extract table data
            table_data = []
            for row in table.find_all('tr'):
                row_data = []
                for cell in row.find_all(['td', 'th']):
                    cell_text = self._clean_text_content(cell.get_text(strip=True))
                    row_data.append(cell_text)
                if row_data:
                    table_data.append(row_data)
            
            if table_data:
                # Create and style the table
                reportlab_table = self._create_styled_table(table_data)
                # Add table to story immediately
                self.story.append(reportlab_table)
                self.story.append(Spacer(1, 12))
            
            # Remove the table from HTML since we've processed it
            table.decompose()
        
        return str(soup)
    
    def _create_styled_table(self, table_data):
        """Create a beautifully styled ReportLab table that fits within page boundaries."""
        if not table_data:
            return None
            
        # Calculate available width (page width minus margins)
        page_width = A4[0]  # 595.27 points
        margin_width = 72 * 2  # 72 points on each side
        available_width = page_width - margin_width  # ~451 points
        
        # Determine number of columns
        max_cols = max(len(row) for row in table_data)
        
        # Calculate column widths - distribute evenly but with minimum/maximum constraints
        base_col_width = available_width / max_cols
        min_col_width = 60  # Minimum 60 points per column
        max_col_width = 150  # Maximum 150 points per column
        
        # Adjust column width if needed
        if base_col_width < min_col_width:
            col_width = min_col_width
        elif base_col_width > max_col_width:
            col_width = max_col_width
        else:
            col_width = base_col_width
            
        # Create column widths list
        col_widths = [col_width] * max_cols
        
        # Wrap text in cells to prevent overflow
        wrapped_table_data = []
        for row in table_data:
            wrapped_row = []
            for i, cell in enumerate(row):
                if len(cell) > 25:  # Wrap long text
                    # Break long text into multiple lines
                    wrapped_text = self._wrap_cell_text(cell, max_chars_per_line=20)
                    wrapped_row.append(wrapped_text)
                else:
                    wrapped_row.append(cell)
            # Pad row to match max columns
            while len(wrapped_row) < max_cols:
                wrapped_row.append('')
            wrapped_table_data.append(wrapped_row)
        
        # Create the table with explicit column widths
        table = Table(wrapped_table_data, colWidths=col_widths, hAlign='CENTER')
        
        # Style the table
        style = TableStyle([
            # Header row styling (first row)
            ('BACKGROUND', (0, 0), (-1, 0), colors.lightblue),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.black),
            ('FONTNAME', (0, 0), (-1, 0), 'latin'),
            ('FONTSIZE', (0, 0), (-1, 0), 9),  # Reduced font size
            ('ALIGN', (0, 0), (-1, 0), 'CENTER'),
            ('VALIGN', (0, 0), (-1, 0), 'MIDDLE'),
            
            # Data rows styling
            ('FONTNAME', (0, 1), (-1, -1), 'latin'),
            ('FONTSIZE', (0, 1), (-1, -1), 8),  # Smaller font for data
            ('ALIGN', (0, 1), (-1, -1), 'LEFT'),
            ('VALIGN', (0, 1), (-1, -1), 'TOP'),
            
            # Grid and borders
            ('GRID', (0, 0), (-1, -1), 0.5, colors.black),
            ('LINEBELOW', (0, 0), (-1, 0), 1, colors.black),
            
            # Alternating row colors for better readability
            ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.lightgrey]),
            
            # Reduced padding to save space
            ('LEFTPADDING', (0, 0), (-1, -1), 4),
            ('RIGHTPADDING', (0, 0), (-1, -1), 4),
            ('TOPPADDING', (0, 0), (-1, -1), 3),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 3),
            
            # Word wrap for long content
            ('WORDWRAP', (0, 0), (-1, -1), 'LTR'),
        ])
        
        table.setStyle(style)
        return table
        
    def _wrap_cell_text(self, text, max_chars_per_line=20):
        """Wrap long text to fit in table cells."""
        if len(text) <= max_chars_per_line:
            return text
            
        words = text.split()
        lines = []
        current_line = []
        current_length = 0
        
        for word in words:
            if current_length + len(word) + 1 <= max_chars_per_line:
                current_line.append(word)
                current_length += len(word) + 1
            else:
                if current_line:
                    lines.append(' '.join(current_line))
                current_line = [word]
                current_length = len(word)
        
        if current_line:
            lines.append(' '.join(current_line))
            
        return '\n'.join(lines)

    def _process_lists(self, content: str) -> str:
        """Convert HTML lists to text with bullets."""
        soup = BeautifulSoup(content, 'html.parser')
        
        for ul in soup.find_all('ul'):
            list_items = []
            for li in ul.find_all('li'):
                text = li.get_text(strip=True)
                if text:
                    list_items.append(f'• {text}')
            
            if list_items:
                list_replacement = '<br/>'.join(list_items)
                ul.replace_with(list_replacement)
        
        return str(soup)

    def _normalize_html_tags(self, content: str) -> str:
        """Normalize HTML tags for ReportLab compatibility."""
        # Convert various break formats
        content = content.replace('<br/>', '<br />').replace('<br>', '<br />')
        
        # Convert paragraph tags (ReportLab handles paragraphs differently)
        content = content.replace('<p>', '').replace('</p>', '<br /><br />')
        
        # Convert em to i, strong to b (ReportLab compatible)
        content = re.sub(r'<em>(.*?)</em>', r'<i>\1</i>', content, flags=re.IGNORECASE | re.DOTALL)
        content = re.sub(r'<strong>(.*?)</strong>', r'<b>\1</b>', content, flags=re.IGNORECASE | re.DOTALL)
        
        # Remove style attributes and divs (keep content)
        content = re.sub(r'<div[^>]*>', '', content, flags=re.IGNORECASE)
        content = re.sub(r'</div>', '', content, flags=re.IGNORECASE)
        
        # Clean up footer elements
        content = re.sub(r'</?footer[^>]*>', '', content, flags=re.IGNORECASE)
        
        return content

    def _clean_text_content(self, content: str) -> str:
        """Clean text content for ReportLab processing."""
        if not content:
            return ""
            
        # Remove any remaining HTML tags except allowed ones
        soup = BeautifulSoup(content, 'html.parser')
        
        # Extract text while preserving some formatting
        text = str(soup)
        
        # Decode HTML entities
        text = html.unescape(text)
        
        # Clean up whitespace
        text = re.sub(r'\s+', ' ', text).strip()
        
        # Remove empty lines
        text = re.sub(r'(<br\s*/?>){3,}', '<br /><br />', text)
        
        return text 