package com.tariff.tariff_backend;

import com.tariff.tariff_backend.dto.PasswordUpdateDTO;
import com.tariff.tariff_backend.dto.TariffPatchDTO;
import com.tariff.tariff_backend.dto.UserManagementDTO;
import com.tariff.tariff_backend.dto.UsernameUpdateDTO;
import com.tariff.tariff_backend.model.Role;
import com.tariff.tariff_backend.model.User;
import com.tariff.tariff_backend.model.auth.AuthResponse;
import com.tariff.tariff_backend.model.dashboard.DashboardMetrics;
import com.tariff.tariff_backend.model.dashboard.DashboardResponse;
import com.tariff.tariff_backend.model.history.HistoricalPoint;
import com.tariff.tariff_backend.model.history.HistoricalResponse;
import com.tariff.tariff_backend.model.history.HistoryPreset;
import com.tariff.tariff_backend.model.user_management.PasswordUpdateResponse;
import com.tariff.tariff_backend.model.user_management.UserManagementResponse;
import com.tariff.tariff_backend.model.user_management.UserResponse;
import com.tariff.tariff_backend.model.user_management.UsernameUpdateResponse;
import org.junit.jupiter.api.Test;
import org.springframework.security.core.authority.SimpleGrantedAuthority;

import java.time.LocalDate;
import java.util.Collections;
import java.util.UUID;

import static org.junit.jupiter.api.Assertions.*;

/**
 * This test class is for simple DTOs and Models (like those generated by Lombok)
 * to ensure getters, setters, constructors, and builders work as expected
 * and to increase test coverage from 0%.
 */
class DtoAndModelTest {

    @Test
    void testUserManagementDTO() {
        UUID id = UUID.randomUUID();
        UserManagementDTO dto1 = new UserManagementDTO(id, "user", "admin");
        UserManagementDTO dto2 = new UserManagementDTO(null, "user2", "user");
        dto2.setId(id);
        
        assertEquals(id, dto1.getId());
        assertEquals("user", dto1.getUsername());
        assertEquals("admin", dto1.getRole());
        
        UserManagementDTO dto3 = UserManagementDTO.builder()
            .id(id).username("user").role("admin").build();
        assertEquals(dto1, dto3);
        assertEquals(dto1.hashCode(), dto3.hashCode());
        assertTrue(dto1.toString().contains("user"));
    }

    @Test
    void testTariffPatchDTO() {
        TariffPatchDTO dto = new TariffPatchDTO();
        dto.setTariffId("123");
        assertEquals("123", dto.getTariffId());
        
        TariffPatchDTO dto2 = new TariffPatchDTO("123", "Desc", "P", "R", "kg", "Cat", null, null, null, null, "Src", 2023);
        assertEquals("Desc", dto2.getDescriptionwcountry());
        assertEquals(2023, dto2.getYear());
    }

    @Test
    void testUserAndRoleModels() {
        Role role = Role.builder().id(1).name("admin").build();
        assertEquals(1, role.getId());

        User user = User.builder()
            .id(UUID.randomUUID())
            .username("admin")
            .password("pass")
            .role(role)
            .build();
            
        assertEquals("admin", user.getUsername());
        assertTrue(user.isAccountNonExpired());
        assertTrue(user.isAccountNonLocked());
        assertTrue(user.isCredentialsNonExpired());
        assertTrue(user.isEnabled());
        assertEquals(Collections.singletonList(new SimpleGrantedAuthority("admin")), user.getAuthorities());
    }

    @Test
    void testAuthResponse() {
        AuthResponse res = AuthResponse.builder().success(true).message("ok").accessToken("token").build();
        assertTrue(res.getSuccess());
        assertEquals("ok", res.getMessage());
        assertEquals("token", res.getAccessToken());
    }

    @Test
    void testDashboardModels() {
        DashboardResponse res = new DashboardResponse(true, "ok");
        assertTrue(res.getSuccess());
        
        DashboardMetrics metrics = new DashboardMetrics(Collections.emptyList(), 0, 1, 10);
        assertEquals(1, metrics.getTotalPages());
    }

    @Test
    void testHistoryModels() {
        HistoricalPoint p = new HistoricalPoint(LocalDate.now(), 10.5);
        p.setValue(11.0);
        assertEquals(11.0, p.getValue());

        HistoricalResponse res = new HistoricalResponse();
        res.setReporter("USA");
        assertEquals("USA", res.getReporter());

        HistoryPreset pre = new HistoryPreset("Title", "R", "P", "123");
        assertEquals("Title", pre.getTitle());
    }

    @Test
    void testUserManagementModels() {
        UserManagementResponse res = UserManagementResponse.builder().message("ok").build();
        assertEquals("ok", res.getMessage());

        UserResponse res2 = UserResponse.builder().message("ok").build();
        assertEquals("ok", res2.getMessage());

        UsernameUpdateResponse res3 = UsernameUpdateResponse.builder().newUsername("new").build();
        assertEquals("new", res3.getNewUsername());

        PasswordUpdateResponse res4 = PasswordUpdateResponse.builder().message("ok").build();
        assertEquals("ok", res4.getMessage());
    }

    @Test
    void testUpdateDTOs() {
        UsernameUpdateDTO userDto = UsernameUpdateDTO.builder().username("new").build();
        assertEquals("new", userDto.getUsername());

        PasswordUpdateDTO passDto = PasswordUpdateDTO.builder().password("pass").build();
        assertEquals("pass", passDto.getPassword());
    }
}