name: Deploy Frontend to S3 and CloudFront

on:
  push:
    branches:
      # - main
      - feat/infra
    paths:
      - 'tariff-frontend/**'                    # Triggers only on changes within the frontend code
      - '.github/workflows/deploy-frontend.yml' # Always run if the workflow itself changes

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    env:
      AWS_REGION: ap-southeast-1

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies and build
        run: |
          cd tariff-frontend/
          npm install
          npm run build

      - name: Sync dist to S3
        run: |
          aws s3 sync tariff-frontend/dist s3://${{ secrets.S3_BUCKET_NAME }} --delete

      - name: Create CloudFront Invalidation
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} \
            --paths "/*"
